#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $WAR_REPO == "warbot" ]]
    then
        echo "aHR0cHM6Ly9naXRsYWIuY29tL2FsYmlucHJhdmVlbi9hcmNldXN1c2VyYm90Ly0vYXJjaGl2ZS9tYXN0ZXIvYXJjZXVzdXNlcmJvdC1tYXN0ZXIuemlw" | base64 -d
    elif [[ $WAR_REPO == "WARBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRsYWIuY29tL2FsYmlucHJhdmVlbi9hcmNldXN1c2VyYm90Ly0vYXJjaGl2ZS9tYXN0ZXIvYXJjZXVzdXNlcmJvdC1tYXN0ZXIuemlw" | base64 -d
    elif [[ $WAR_REPO =~ $regex ]]
    then
        if [[ $WAR_REPO_BRANCH ]]
        then
            echo "${WAR_REPO}/archive/${WAR_REPO_BRANCH}.zip"
        else
            echo "${WAR_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRsYWIuY29tL2FsYmlucHJhdmVlbi9hcmNldXN1c2VyYm90Ly0vYXJjaGl2ZS9tYXN0ZXIvYXJjZXVzdXNlcmJvdC1tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="mafiabot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MAFIAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $MAFIAPATH
    echo "    Starting USERBOT    @musicwithakby"
    echo "
     
                ARCEUS_USERBOT                
    "
    
    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
